### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by xu1110** [huangzichun/Concept4CRS#1]
Hi, nice work!
We are interested in your work and trying to run this code. But it looks like some files are missing, such as "../data/profile.csv".
Could you please share these files?
Thanks.

**Comment by huangzichun** [comment]
Sorry for that.

We just uploaded the data folder.

**Comment by huangzichun** [comment]
Hi, @xu1110 

Sorry for that. We just uploaded the data folder :)

**Comment by xu1110** [comment]
Hi, @huangzichun
Thanks for your sharing. Now I can successfully run this code.
